### PR TITLE
[FIX]: changes policy and rule to be more focussed name in kube-bench-adapter

### LINKED ISSUE #101: The policy and rule name is generic for multiple policy violation generation
Today we using a generic name for policy and rule in multiple policy violation. Need to a have focused name for policy and rule each policy violations
```
- category: CIS Benchmarks
  message: Ensure that the controller manager pod specification file permissions are
    set to 644 or more restrictive (Automated)
  policy: Master Node Security Configuration
  properties:
    AuditConfig: ""
    AuditEnv: ""
    IsMultiple: "false"
    actual_value: permissions=600
    audit: /bin/sh -c 'if test -e /etc/kubernetes/manifests/kube-controller-manager.yaml;
      then stat -c permissions=%a /etc/kubernetes/manifests/kube-controller-manager.yaml;
      fi'
    expected_result: permissions has permissions 600, expected 644 or more restrictive
    index: 1.1.3
    reason: ""
    remediation: |
      Run the below command (based on the file location on your system) on the master node.
      For example,
      chmod 644 /etc/kubernetes/manifests/kube-controller-manager.yaml
    test_info: |
      Run the below command (based on the file location on your system) on the master node.
      For example,
      chmod 644 /etc/kubernetes/manifests/kube-controller-manager.yaml
    type: ""
  result: pass
  rule: Master Node Configuration Files
  scored: true
  source: ""
  timestamp:
    nanos: 0
    seconds: 0
- category: CIS Benchmarks
  message: Ensure that the controller manager pod specification file ownership is
    set to root:root (Automated)
  policy: Master Node Security Configuration
  properties:
    AuditConfig: ""
    AuditEnv: ""
    IsMultiple: "false"
    actual_value: root:root
    audit: /bin/sh -c 'if test -e /etc/kubernetes/manifests/kube-controller-manager.yaml;
      then stat -c %U:%G /etc/kubernetes/manifests/kube-controller-manager.yaml; fi'
    expected_result: '''root:root'' is present'
    index: 1.1.4
    reason: ""
    remediation: |
      Run the below command (based on the file location on your system) on the master node.
      For example,
      chown root:root /etc/kubernetes/manifests/kube-controller-manager.yaml
    test_info: |
      Run the below command (based on the file location on your system) on the master node.
      For example,
      chown root:root /etc/kubernetes/manifests/kube-controller-manager.yaml
    type: ""
  result: pass
  rule: Master Node Configuration Files
  scored: true
  source: ""
  timestamp:
    nanos: 0
    seconds: 0
- category: CIS Benchmarks
  message: Ensure that the scheduler pod specification file permissions are set to
    644 or more restrictive (Automated)
  policy: Master Node Security Configuration
  properties:
    AuditConfig: ""
    AuditEnv: ""
    IsMultiple: "false"
    actual_value: permissions=600
    audit: /bin/sh -c 'if test -e /etc/kubernetes/manifests/kube-scheduler.yaml; then
      stat -c permissions=%a /etc/kubernetes/manifests/kube-scheduler.yaml; fi'
    expected_result: permissions has permissions 600, expected 644 or more restrictive
    index: 1.1.5
    reason: ""
    remediation: |
      Run the below command (based on the file location on your system) on the master node.
      For example,
      chmod 644 /etc/kubernetes/manifests/kube-scheduler.yaml
    test_info: |
      Run the below command (based on the file location on your system) on the master node.
      For example,
      chmod 644 /etc/kubernetes/manifests/kube-scheduler.yaml
    type: ""
  result: pass
  rule: Master Node Configuration Files
  scored: true
  source: ""
  timestamp:
    nanos: 0
    seconds: 0
```

### PR DESCRIPTION
**Pull request by mritunjaysharma394**
This PR aims to fix #101 by making `policy` and `rule` having more focused names in kube-bench-adapter

(Note: for now it changed just `policy` name, little more confirmation required for `rule` mapping)

The updated policy would like:

```yaml
 - category: CIS Benchmarks
    message: Ensure that the etcd data directory ownership is set to etcd:etcd (Automated)
    policy: 1.1.12  Master Node Security Configuration 
    properties:
      AuditConfig: ""
      AuditEnv: ""
      IsMultiple: "false"
      actual_value: root:root
      audit: ps -ef | grep etcd | grep -- --data-dir | sed 's%.*data-dir[= ]\([^ ]*\).*%\1%'
        | xargs stat -c %U:%G
      expected_result: '''etcd:etcd'' is present'
      index: 1.1.12
      reason: ""
      remediation: |
        On the etcd server node, get the etcd data directory, passed as an argument --data-dir,
        from the below command:
        ps -ef | grep etcd
        Run the below command (based on the etcd data directory found above).
        For example, chown etcd:etcd /var/lib/etcd
      test_info: |
        On the etcd server node, get the etcd data directory, passed as an argument --data-dir,
        from the below command:
        ps -ef | grep etcd
        Run the below command (based on the etcd data directory found above).
        For example, chown etcd:etcd /var/lib/etcd
      type: ""
    result: fail
    rule: Master Node Configuration Files
    scored: true
    source: Kube Bench
    timestamp:
      nanos: 585074788
      seconds: 36
  - category: CIS Benchmarks
    message: Ensure that the admin.conf file permissions are set to 644 or more restrictive
      (Automated)
    policy: 1.1.13 Master Node Security Configuration 
    properties:
      AuditConfig: ""
      AuditEnv: ""
      IsMultiple: "false"
      actual_value: permissions=600
      audit: /bin/sh -c 'if test -e /etc/kubernetes/admin.conf; then stat -c permissions=%a
        /etc/kubernetes/admin.conf; fi'
      expected_result: permissions has permissions 600, expected 644 or more restrictive
      index: 1.1.13
      reason: ""
      remediation: |
        Run the below command (based on the file location on your system) on the master node.
        For example,
        chmod 644 /etc/kubernetes/admin.conf
      test_info: |
        Run the below command (based on the file location on your system) on the master node.
        For example,
        chmod 644 /etc/kubernetes/admin.conf
      type: ""
    result: pass
    rule: Master Node Configuration Files
    scored: true
    source: Kube Bench
    timestamp:
      nanos: 585075739
      seconds: 36
  - category: CIS Benchmarks
    message: Ensure that the admin.conf file ownership is set to root:root (Automated)
    policy: 1.1.14  Master Node Security Configuration 
    properties:
      AuditConfig: ""
      AuditEnv: ""
      IsMultiple: "false"
      actual_value: root:root
      audit: /bin/sh -c 'if test -e /etc/kubernetes/admin.conf; then stat -c %U:%G
        /etc/kubernetes/admin.conf; fi'
      expected_result: '''root:root'' is present'
      index: 1.1.14
      reason: ""
      remediation: |
        Run the below command (based on the file location on your system) on the master node.
        For example,
        chown root:root /etc/kubernetes/admin.conf
      test_info: |
        Run the below command (based on the file location on your system) on the master node.
        For example,
        chown root:root /etc/kubernetes/admin.conf
      type: ""
    result: pass
    rule: Master Node Configuration Files
    scored: true
    source: Kube Bench
    timestamp:
      nanos: 585076620
      seconds: 36
   ```
   
Note: The above policy also shows the changes that #103 will fix (that is timestamp)

Signed-off-by: Mritunjay Sharma <mritunjaysharma394@gmail.com>

cc @JimBugwadia @realshuting

### CODE REVIEW

File: policy-report/kube-bench-adapter/pkg/report/create.go [hunk 1]
```diff
@@ -40,7 +40,7 @@ func New(cisResults *kubebench.OverallControls, name string, category string) (*
 
 func newResult(category string, control *kubebench.Controls, group *kubebench.Group, check *kubebench.Check) *clusterpolicyreport.PolicyReportResult {
 	return &clusterpolicyreport.PolicyReportResult{
-		Policy:      control.Text,
+		Policy:      check.ID + " " + control.Text,
```
Comment (JimBugwadia) [inline policy-report/kube-bench-adapter/pkg/report/create.go:43]: Can we use a "-" for the delimiter, instead of a space?

Are there any restrictions on the length of the policy name? If so, we may need to trim the string to meet that.

**Review by JimBugwadia — CHANGES_REQUESTED** [review]

File: policy-report/kube-bench-adapter/pkg/report/create.go (hunk 1 above)
Comment (mritunjaysharma394) [reply policy-report/kube-bench-adapter/pkg/report/create.go:43]: Sure thing, @JimBugwadia! Will check and update accordingly!

Comment (mritunjaysharma394) [reply policy-report/kube-bench-adapter/pkg/report/create.go]: I fixed the delimiter part but I am not sure if `Policy` name uses RFC1123 or RFC1035 or does it even have such restrictions?
Here's a [link](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names) that I referred to.  


Thanks a lot!

Comment (JimBugwadia) [reply policy-report/kube-bench-adapter/pkg/report/create.go]: Ho @mritunjaysharma394 - you can check the CRD for this. It does not look like there are any length constraints defined:

https://github.com/kubernetes-sigs/wg-policy-prototypes/blob/master/policy-report/crd/v1alpha2/wgpolicyk8s.io_policyreports.yaml#L72

Comment (mritunjaysharma394) [reply policy-report/kube-bench-adapter/pkg/report/create.go]: Oh got it, I guess then it is good to merge then right?

**Review by JimBugwadia — APPROVED** [review]
